name: Auto Update Daily Study Feed

permissions:
  contents: write

on:
  schedule:
    - cron: '0 10 * * *'      # 10 UTC ≈ 05 EST / 06 EDT
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout feed source
      uses: actions/checkout@v3
      with:
        repository: hyper-liquidated/daily-study-digest-source
        ref: main                  # change if the default branch is ‘master’ etc.
        path: source
        # If the source repo is private, create a PAT secret called SOURCE_PAT
        # and uncomment the next line:
        # token: ${{ secrets.SOURCE_PAT }}

    - name: Copy feed file
      run: cp source/path/to/daily_study_digest.xml .

    - name: Commit & push if changed
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add daily_study_digest.xml
        if ! git diff --cached --quiet; then
          git commit -m "Daily RSS update"
          git push
        else
          echo "No changes – nothing to commit."
        fi
