name: Auto Update Daily Study Feed

# Let the workflow’s default GITHUB_TOKEN commit to this repo
permissions:
  contents: write

on:
  # Every day at 10 UTC  (≈ 06 EDT / 05 EST)
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:        # manual “Run workflow” button

jobs:
  refresh-feed:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out THIS repository (daily-study-digest)
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0          # keep history so git diff can compare

      # 2) Download the latest feed from the live site
      - name: Download latest feed
        run: |
          curl -fsSL -o daily_study_digest.xml \
            https://hyper-liquidated.github.io/daily-study-digest/daily_study_digest.xml

      # 3) Commit & push ONLY if the file changed
      - name: Commit and push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add daily_study_digest.xml
          if ! git diff --cached --quiet; then
            git commit -m "Auto-refresh daily_study_digest.xml"
            git push
          else
            echo "No changes – nothing to commit."
          fi
