name: Auto Update Daily Study Feed

permissions:
  contents: write          # ← enables git push

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    # 1) Checkout THIS pages repo – do NOT persist its token
- name: Checkout pages repo
  uses: actions/checkout@v3
  with:
    path: pages
    persist-credentials: false      # prevents 403 later

# 2) Checkout the SOURCE repo
#    • If source repo is public → leave token blank
#    • If private → use    token: ${{ secrets.SOURCE_PAT }}
- name: Checkout study-source repo
  uses: actions/checkout@v3
  with:
    repository: hyper-liquidated/study-source   # owner/repo of Repo A
    token: ""                                   # "" for public repo
    path: source


      # 3) Copy the fresh JSON into pages/data
      - name: Copy studies.json
        run: |
          cp source/data/studies.json pages/data/studies.json

      # 4) Build homepage & RSS from that JSON
      - name: Build & render
        run: |
          cd pages
          python scripts/generate_feed.py

            # 5) Commit & push if changed
      - name: Commit & publish
        run: |
          cd pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/studies.json index.html daily_study_digest.xml
          git diff --cached --quiet || git commit -m "Auto-regenerate homepage"

          # --- inject the GITHUB_TOKEN for this repo into the remote URL ---
          git remote set-url origin \
            https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          git push origin main   # now authenticated

