name: Auto Update Homepage

permissions:
  contents: write

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update-homepage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate index.html
        run: python scripts/generate_feed.py

      - name: Commit & push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git diff --quiet --cached || git commit -m "Auto-regenerate homepage"
          git push