name: Auto Update Daily Study Feed
on:
  schedule:
    # 09:00 UTC = 5 AM ET
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # A) Checkout this Pages repo
      - uses: actions/checkout@v3
        with:
          path: pages

      # B) Checkout your source repo
      - uses: actions/checkout@v3
        with:
          repository: hyper-liquidated/study-source
          path: source

      # C) Copy fresh JSON
      - name: Copy new studies.json
        run: |
          cp source/data/studies.json pages/data/studies.json

      # D) Build HTML & RSS
      - name: Build feed & page
        run: |
          cd pages
          python scripts/generate_feed.py

      # E) Commit & push
      - name: Commit & publish
        run: |
          cd pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/studies.json index.html daily_study_digest.xml
          git diff --cached --quiet || git commit -m "Auto-regenerate homepage"
          git push origin main
