# .github/workflows/update-homepage.yml
name: Auto Update Homepage

# 1) Give the workflow explicit write access to `contents`
permissions:
  contents: write

on:
  workflow_dispatch:  # only when you click “Run workflow” by hand

jobs:
  update-homepage:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout and persist the GITHUB_TOKEN credentials
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate index.html
        run: python scripts/generate_feed.py

      - name: Commit & push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git diff --cached --quiet \
            || git commit -m "Rebuild homepage with DOI links"
          git push