name: Auto Update Daily Study Feed

permissions:
  contents: write          # allow the default GITHUB_TOKEN to push

on:
  schedule:
    - cron: '0 10 * * *'   # 10 UTC → 05 EST / 06 EDT
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out this repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Download the latest feed from the source repo (raw file URL)
      - name: Download latest RSS feed
        run: |
          curl -fsSL -o daily_study_digest.xml \
            https://raw.githubusercontent.com/hyper-liquidated/daily-study-digest-source/main/rss.xml

      # 3) Commit & push only when the file changed
      - name: Commit and push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add daily_study_digest.xml
          if ! git diff --cached --quiet; then
            git commit -m "Daily RSS update"
            git push
          else
            echo "No changes – nothing to commit."
          fi
