name: Auto Update Daily Study Feed

# Give the workflow token write-access so it can push back to this repo
permissions:
  contents: write

on:
  schedule:
    - cron: '0 9 * * *'      # 09 UTC → 05 AM ET (summer) / 04 AM ET (winter)
  workflow_dispatch:         # manual trigger button

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    # ──────────────────────────────────────────────────────────────
    # 1) Checkout THIS Pages repo
    - name: Checkout pages repo
      uses: actions/checkout@v3
      with:
        path: pages
        persist-credentials: false   # prevents 403 when cloning source repo

    # ──────────────────────────────────────────────────────────────
    # 2) Checkout the SOURCE repo that contains the fresh studies.json
    - name: Checkout study-source repo
      uses: actions/checkout@v3
      with:
        repository: hyper-liquidated/study-source   # owner/repo of source
        path: source
        # If the source repo ever becomes PRIVATE, create a secret called
        # SOURCE_PAT (scoped to `repo`) and uncomment the next line:
        # token: ${{ secrets.SOURCE_PAT }}

    # ──────────────────────────────────────────────────────────────
    # 3) Copy the fresh JSON into this repo’s data folder
    - name: Copy studies.json
      run: cp source/data/studies.json pages/data/studies.json

    # ──────────────────────────────────────────────────────────────
    # 4) Rebuild homepage & RSS
    - name: Build homepage & RSS
      run: |
        cd pages
        python scripts/generate_feed.py

    # ──────────────────────────────────────────────────────────────
    # 5) Commit & push the changes (uses write-scoped GITHUB_TOKEN)
    - name: Commit & publish
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO:  ${{ github.repository }}
      run: |
        cd pages
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add data/studies.json index.html daily_study_digest.xml

        if ! git diff --cached --quiet; then
          git commit -m "Auto-regenerate homepage"

          # authenticate push with the workflow token
          git remote set-url origin \
            https://x-access-token:${TOKEN}@github.com/${REPO}.git

          git push origin HEAD:main
        else
          echo "No changes – nothing to push."
        fi
