name: Auto Update Daily Study Feed

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 5:00 AM EST
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Download the latest RSS feed
        run: curl -o daily_study_digest.xml https://hyper-liquidated.github.io/daily-study-digest-source/rss.xml

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add daily_study_digest.xml
          git diff --cached --quiet || git commit -m "Daily RSS update"
          git push
