name: Auto Update Daily Study Feed

permissions:
  contents: write

on:
  schedule:
    - cron: '0 9 * * *'          # 09 UTC = 5 AM ET
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout THIS Pages repo into folder “pages”
      - name: Checkout pages repo
        uses: actions/checkout@v3
        with:
          path: pages

      # 2) Checkout the SOURCE repo (study-source) into folder “source”
      - name: Checkout study-source repo
        uses: actions/checkout@v3            # ← same action
        with:
          repository: hyper-liquidated/study-source   # owner/repo of Repo A
          token: ${{ secrets.SOURCE_PAT }}             # PAT you just added
          path: source

      # 3) Copy the fresh JSON into pages/data
      - name: Copy studies.json
        run: |
          cp source/data/studies.json pages/data/studies.json

      # 4) Build homepage & RSS from that JSON
      - name: Build & render
        run: |
          cd pages
          python scripts/generate_feed.py

      # 5) Commit & publish if anything changed
      - name: Commit & push
        run: |
          cd pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/studies.json index.html daily_study_digest.xml
          git diff --cached --quiet || git commit -m "Auto-regenerate homepage"
          git push origin main
